# Generated by Django 4.2.30 on 2026-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_avaliacao_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
